#!/usr/bin/env node
// WONKYARD — End of Day recap.
//
// Run when the Founder says "퇴근" / "오늘 마무리" / "call it a day". It gathers
// everything that moved today from state/company.db and git, then writes (or
// refreshes) reports/daily/<YYYY-MM-DD>.md. The auto-generated facts live between
// AUTO markers; anything the Chief of Staff writes by hand around them is kept on
// re-runs.
//
// Usage:
//   node scripts/eod.mjs                 # today (local date)
//   node scripts/eod.mjs --date 2026-08-30
//   node scripts/eod.mjs --print         # print the facts, don't write the file
//
// Portability: no npm dependencies. It shells out to `sqlite3` (the same tool the
// rest of the company system assumes). If `sqlite3` is not on PATH, set the
// SQLITE3 env var to its full path, e.g.
//   SQLITE3="C:/Users/me/anaconda3/Library/bin/sqlite3.exe" node scripts/eod.mjs
// The git and filesystem sections still work without it.

import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const DB = join(ROOT, 'state', 'company.db');

const AUTO_BEGIN = '<!-- AUTO:BEGIN — regenerated by scripts/eod.mjs, do not edit inside -->';
const AUTO_END = '<!-- AUTO:END -->';

// ---- args ----------------------------------------------------------------
const args = process.argv.slice(2);
const printOnly = args.includes('--print');
const dateArg = (() => {
  const i = args.indexOf('--date');
  return i >= 0 ? args[i + 1] : null;
})();

const day = dateArg || localDateISO(new Date());
if (!/^\d{4}-\d{2}-\d{2}$/.test(day)) {
  console.error(`bad --date "${day}" — expected YYYY-MM-DD`);
  process.exit(2);
}
const nextDay = localDateISO(new Date(Date.parse(day + 'T00:00:00Z') + 86400000));

function localDateISO(d) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

// ---- sqlite -------------------------------------------------------------
function findSqlite() {
  const candidates = [
    process.env.SQLITE3,
    'sqlite3',
    join(process.env.USERPROFILE || process.env.HOME || '', 'anaconda3/Library/bin/sqlite3.exe'),
    join(process.env.USERPROFILE || process.env.HOME || '', 'scoop/shims/sqlite3.exe'),
    '/usr/bin/sqlite3',
    '/opt/homebrew/bin/sqlite3',
  ].filter(Boolean);
  for (const c of candidates) {
    try {
      execFileSync(c, ['-version'], { stdio: 'pipe' });
      return c;
    } catch { /* try next */ }
  }
  return null;
}

const SQLITE = existsSync(DB) ? findSqlite() : null;

function q(sql) {
  if (!SQLITE) return null;
  try {
    const out = execFileSync(SQLITE, ['-readonly', '-json', DB, sql], { encoding: 'utf8', stdio: 'pipe' });
    return out.trim() ? JSON.parse(out) : [];
  } catch (e) {
    return { error: String(e.stderr || e.message).trim() };
  }
}

// day-scoped predicate: company.db timestamps are `datetime('now')` = UTC.
// We match on the date prefix, which is what every existing query does.
const onDay = (col) => `substr(${col},1,10) = '${day}'`;

// ---- gather -----------------------------------------------------------
const statusRows = q(`SELECT ts, project_id, department, status, note FROM status_log WHERE ${onDay('ts')} ORDER BY ts;`);
const gateRows = q(`SELECT ts, project_id, gate, decision, reason FROM gate_decisions WHERE ${onDay('ts')} ORDER BY ts;`);
const stageRows = q(`SELECT project_id, current_stage, updated_at FROM projects WHERE ${onDay('updated_at')} ORDER BY updated_at;`);
const projReports = q(`SELECT project_id, summary, detail_path FROM project_reports WHERE report_date = '${day}' ORDER BY project_id;`);

function git(cmdArgs) {
  try {
    return execFileSync('git', cmdArgs, { cwd: ROOT, encoding: 'utf8', stdio: 'pipe' }).trim();
  } catch (e) {
    return '';
  }
}
const commits = git(['log', `--since=${day} 00:00`, `--until=${nextDay} 00:00`, '--pretty=format:%h  %s']);

// reports/ is gitignored, so list working-tree report files whose mtime falls on
// the day. Pure Node fs — no shell, no platform branch, no console-encoding trap.
const touchedReports = (() => {
  const dir = join(ROOT, 'reports');
  if (!existsSync(dir)) return [];
  const lo = Date.parse(day + 'T00:00:00');       // local midnight
  const hi = Date.parse(nextDay + 'T00:00:00');
  const hits = [];
  const walk = (d) => {
    for (const ent of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, ent.name);
      if (ent.isDirectory()) walk(p);
      else {
        const m = statSync(p).mtimeMs;
        if (m >= lo && m < hi) hits.push(relative(ROOT, p).replace(/\\/g, '/'));
      }
    }
  };
  walk(dir);
  return hits.sort();
})();

// ---- render ----------------------------------------------------------
function table(rows, cols) {
  if (!rows || rows.error) return `_(${rows?.error ? 'query failed: ' + rows.error : 'no sqlite3 — set SQLITE3 env var'})_\n`;
  if (rows.length === 0) return '_(none)_\n';
  const head = `| ${cols.join(' | ')} |\n| ${cols.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${cols.map((c) => String(r[c] ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')).join(' | ')} |`).join('\n');
  return head + '\n' + body + '\n';
}

const facts = [
  AUTO_BEGIN,
  '',
  `_Generated ${new Date().toISOString()} by \`scripts/eod.mjs\`._`,
  '',
  '### Gate decisions today',
  '',
  table(gateRows, ['ts', 'project_id', 'gate', 'decision', 'reason']),
  '### Project stage changes today',
  '',
  table(stageRows, ['project_id', 'current_stage', 'updated_at']),
  '### Department activity today (status_log)',
  '',
  table(statusRows, ['ts', 'project_id', 'department', 'status', 'note']),
  '### Per-repo daily roll-ups (project_reports)',
  '',
  table(projReports, ['project_id', 'summary', 'detail_path']),
  '### Company-repo commits today',
  '',
  commits ? '```\n' + commits + '\n```\n' : '_(none)_\n',
  '### Report files touched today',
  '',
  touchedReports.length ? touchedReports.map((p) => `- \`${p}\``).join('\n') + '\n' : '_(none)_\n',
  AUTO_END,
].join('\n');

if (printOnly) {
  console.log(facts);
  process.exit(0);
}

// ---- write, preserving hand-written narrative -------------------------
const outDir = join(ROOT, 'reports', 'daily');
mkdirSync(outDir, { recursive: true });
const outFile = join(outDir, `${day}.md`);

const template = (autoBlock) => `# WONKYARD — ${day} (End of Day)

${autoBlock}

## What actually happened

_(Chief of Staff: 2–5 lines, plain language — what moved, what shipped.)_

## Open threads

_(carry-over items, one line each)_

## Blocked on Founder

_(explicit asks — what only the Founder can unblock, and the exact step)_

## Tomorrow — priority order

1.
2.
3.
`;

let next;
if (existsSync(outFile)) {
  const prev = readFileSync(outFile, 'utf8');
  if (prev.includes(AUTO_BEGIN) && prev.includes(AUTO_END)) {
    next = prev.replace(
      new RegExp(escapeRe(AUTO_BEGIN) + '[\\s\\S]*?' + escapeRe(AUTO_END)),
      facts
    );
  } else {
    // older hand-made file — prepend the auto block, keep their text below.
    next = prev.replace(/^(# .*\n)/, `$1\n${facts}\n`);
    if (next === prev) next = facts + '\n\n' + prev;
  }
} else {
  next = template(facts);
}
writeFileSync(outFile, next);

function escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

// ---- terminal summary ------------------------------------------------
const n = (r) => (Array.isArray(r) ? r.length : 0);
console.log(`\nEOD ${day} → ${relative(ROOT, outFile).replace(/\\/g, '/')}`);
console.log(`  gate decisions: ${n(gateRows)}   stage changes: ${n(stageRows)}   status rows: ${n(statusRows)}`);
console.log(`  commits: ${commits ? commits.split('\n').length : 0}   report files touched: ${touchedReports.length}`);
if (!SQLITE && existsSync(DB)) console.log('  note: sqlite3 not found — DB sections are empty. Set the SQLITE3 env var.');
console.log('\nNow fill in the narrative sections, then you are clocked out.\n');
